### ISSUE TITLE
Analyzer crash while logging at startup

### ISSUE THREAD

**Issue by creachadair** [src-d/lookout-sonarcheck-analyzer#18]
From https://github.com/src-d/empathy-sessions/issues/31.

**Synopsis:** The sonarcheck analyzer throws a Python exception at startup, while attempting to log (`TypeError: %d format: a number is required, not str`).

**Repro:**

This is more or less following the instructions for `docker-compose` on https://github.com/src-d/lookout, with some config file tweaks. I'm running on macOS with 

```sh
# Use [1] as config.yml
# Use [2] as docker-compose.yml
$ docker-compose pull
$ docker-compose up --force-recreate
```

[1] https://gist.github.com/creachadair/9be8e1524d9ca6511c277e3ebbd7d722
[2] https://gist.github.com/creachadair/f886b0b3f7a5eb8fda8c866a6b5bf96b

**Expected**: Clean startup.

**Observed:**

```
Attaching to test_sonarcheck_1, test_bblfsh_1, test_postgres_1, test_lookout_1
sonarcheck_1  | --- Logging error ---
sonarcheck_1  | Traceback (most recent call last):
sonarcheck_1  |   File "/usr/local/lib/python3.7/logging/__init__.py", line 1034, in emit
sonarcheck_1  |     msg = self.format(record)
sonarcheck_1  |   File "/usr/local/lib/python3.7/logging/__init__.py", line 880, in format
sonarcheck_1  |     return fmt.format(record)
sonarcheck_1  |   File "/usr/local/lib/python3.7/logging/__init__.py", line 619, in format
sonarcheck_1  |     record.message = record.getMessage()
sonarcheck_1  |   File "/usr/local/lib/python3.7/logging/__init__.py", line 380, in getMessage
sonarcheck_1  |     msg = msg % self.args
sonarcheck_1  | TypeError: %d format: a number is required, not str
sonarcheck_1  | Call stack:
sonarcheck_1  |   File "/bin/sonarcheck_analyzer.py", line 117, in <module>
sonarcheck_1  |     main()
sonarcheck_1  |   File "/bin/sonarcheck_analyzer.py", line 111, in main
sonarcheck_1  |     logger.info("starting gRPC Analyzer server at port %d", port_to_listen)
sonarcheck_1  | Message: 'starting gRPC Analyzer server at port %d'
sonarcheck_1  | Arguments: ('10301',)
sonarcheck_1  | 1 langs, 56 checks supported
```

**Comment by smacker** [comment]
it was fixed by #16
